/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as externalIndexRouteImport } from './routes/(external)/index'
import { Route as mainChatRouteRouteImport } from './routes/(main)/chat/route'
import { Route as mainDashboardRouteRouteImport } from './routes/(main)/dashboard/route'
import { Route as mainMailRouteRouteImport } from './routes/(main)/mail/route'
import { Route as mainUnauthorizedRouteImport } from './routes/(main)/unauthorized'
import { Route as mainAuthForgotPasswordRouteRouteImport } from './routes/(main)/auth/forgot-password/route'
import { Route as mainAuthLoginRouteRouteImport } from './routes/(main)/auth/login/route'
import { Route as mainAuthRegisterRouteRouteImport } from './routes/(main)/auth/register/route'
import { Route as mainAuthResetPasswordRouteRouteImport } from './routes/(main)/auth/reset-password/route'
import { Route as mainAuthVerifyEmailRouteRouteImport } from './routes/(main)/auth/verify-email/route'
import { Route as mainDashboardIndexRouteImport } from './routes/(main)/dashboard/index'
import { Route as mainDashboardSplatRouteImport } from './routes/(main)/dashboard/$'
import { Route as mainDashboardAdaptersRouteRouteImport } from './routes/(main)/dashboard/adapters/route'
import { Route as mainDashboardAnalyticsRouteRouteImport } from './routes/(main)/dashboard/analytics/route'
import { Route as mainDashboardCalendarRouteRouteImport } from './routes/(main)/dashboard/calendar/route'
import { Route as mainDashboardCategoriesRouteRouteImport } from './routes/(main)/dashboard/categories/route'
import { Route as mainDashboardChatRouteRouteImport } from './routes/(main)/dashboard/chat/route'
import { Route as mainDashboardComingSoonRouteRouteImport } from './routes/(main)/dashboard/coming-soon/route'
import { Route as mainDashboardDefaultRouteRouteImport } from './routes/(main)/dashboard/default/route'
import { Route as mainDashboardGeoRouteRouteImport } from './routes/(main)/dashboard/geo/route'
import { Route as mainDashboardInfrastructureRouteRouteImport } from './routes/(main)/dashboard/infrastructure/route'
import { Route as mainDashboardKanbanRouteRouteImport } from './routes/(main)/dashboard/kanban/route'
import { Route as mainDashboardMailRouteRouteImport } from './routes/(main)/dashboard/mail/route'
import { Route as mainDashboardMediaRouteRouteImport } from './routes/(main)/dashboard/media/route'
import { Route as mainDashboardRolesRouteRouteImport } from './routes/(main)/dashboard/roles/route'
import { Route as mainDashboardSeoRouteRouteImport } from './routes/(main)/dashboard/seo/route'
import { Route as mainDashboardSettingsRouteRouteImport } from './routes/(main)/dashboard/settings/route'
import { Route as mainDashboardSocialRouteRouteImport } from './routes/(main)/dashboard/social/route'
import { Route as mainDashboardTasksRouteRouteImport } from './routes/(main)/dashboard/tasks/route'
import { Route as mainDashboardUsersRouteRouteImport } from './routes/(main)/dashboard/users/route'

const externalIndexRoute = externalIndexRouteImport.update({
  id: '/(external)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const mainChatRouteRoute = mainChatRouteRouteImport.update({
  id: '/(main)/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const mainDashboardRouteRoute = mainDashboardRouteRouteImport.update({
  id: '/(main)/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const mainMailRouteRoute = mainMailRouteRouteImport.update({
  id: '/(main)/mail',
  path: '/mail',
  getParentRoute: () => rootRouteImport,
} as any)
const mainUnauthorizedRoute = mainUnauthorizedRouteImport.update({
  id: '/(main)/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const mainAuthForgotPasswordRouteRoute =
  mainAuthForgotPasswordRouteRouteImport.update({
    id: '/(main)/auth/forgot-password',
    path: '/auth/forgot-password',
    getParentRoute: () => rootRouteImport,
  } as any)
const mainAuthLoginRouteRoute = mainAuthLoginRouteRouteImport.update({
  id: '/(main)/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const mainAuthRegisterRouteRoute = mainAuthRegisterRouteRouteImport.update({
  id: '/(main)/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const mainAuthResetPasswordRouteRoute =
  mainAuthResetPasswordRouteRouteImport.update({
    id: '/(main)/auth/reset-password',
    path: '/auth/reset-password',
    getParentRoute: () => rootRouteImport,
  } as any)
const mainAuthVerifyEmailRouteRoute =
  mainAuthVerifyEmailRouteRouteImport.update({
    id: '/(main)/auth/verify-email',
    path: '/auth/verify-email',
    getParentRoute: () => rootRouteImport,
  } as any)
const mainDashboardIndexRoute = mainDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => mainDashboardRouteRoute,
} as any)
const mainDashboardSplatRoute = mainDashboardSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => mainDashboardRouteRoute,
} as any)
const mainDashboardAdaptersRouteRoute =
  mainDashboardAdaptersRouteRouteImport.update({
    id: '/adapters',
    path: '/adapters',
    getParentRoute: () => mainDashboardRouteRoute,
  } as any)
const mainDashboardAnalyticsRouteRoute =
  mainDashboardAnalyticsRouteRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => mainDashboardRouteRoute,
  } as any)
const mainDashboardCalendarRouteRoute =
  mainDashboardCalendarRouteRouteImport.update({
    id: '/calendar',
    path: '/calendar',
    getParentRoute: () => mainDashboardRouteRoute,
  } as any)
const mainDashboardCategoriesRouteRoute =
  mainDashboardCategoriesRouteRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => mainDashboardRouteRoute,
  } as any)
const mainDashboardChatRouteRoute = mainDashboardChatRouteRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => mainDashboardRouteRoute,
} as any)
const mainDashboardComingSoonRouteRoute =
  mainDashboardComingSoonRouteRouteImport.update({
    id: '/coming-soon',
    path: '/coming-soon',
    getParentRoute: () => mainDashboardRouteRoute,
  } as any)
const mainDashboardDefaultRouteRoute =
  mainDashboardDefaultRouteRouteImport.update({
    id: '/default',
    path: '/default',
    getParentRoute: () => mainDashboardRouteRoute,
  } as any)
const mainDashboardGeoRouteRoute = mainDashboardGeoRouteRouteImport.update({
  id: '/geo',
  path: '/geo',
  getParentRoute: () => mainDashboardRouteRoute,
} as any)
const mainDashboardInfrastructureRouteRoute =
  mainDashboardInfrastructureRouteRouteImport.update({
    id: '/infrastructure',
    path: '/infrastructure',
    getParentRoute: () => mainDashboardRouteRoute,
  } as any)
const mainDashboardKanbanRouteRoute =
  mainDashboardKanbanRouteRouteImport.update({
    id: '/kanban',
    path: '/kanban',
    getParentRoute: () => mainDashboardRouteRoute,
  } as any)
const mainDashboardMailRouteRoute = mainDashboardMailRouteRouteImport.update({
  id: '/mail',
  path: '/mail',
  getParentRoute: () => mainDashboardRouteRoute,
} as any)
const mainDashboardMediaRouteRoute = mainDashboardMediaRouteRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => mainDashboardRouteRoute,
} as any)
const mainDashboardRolesRouteRoute = mainDashboardRolesRouteRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => mainDashboardRouteRoute,
} as any)
const mainDashboardSeoRouteRoute = mainDashboardSeoRouteRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => mainDashboardRouteRoute,
} as any)
const mainDashboardSettingsRouteRoute =
  mainDashboardSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => mainDashboardRouteRoute,
  } as any)
const mainDashboardSocialRouteRoute =
  mainDashboardSocialRouteRouteImport.update({
    id: '/social',
    path: '/social',
    getParentRoute: () => mainDashboardRouteRoute,
  } as any)
const mainDashboardTasksRouteRoute = mainDashboardTasksRouteRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => mainDashboardRouteRoute,
} as any)
const mainDashboardUsersRouteRoute = mainDashboardUsersRouteRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => mainDashboardRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/chat': typeof mainChatRouteRoute
  '/dashboard': typeof mainDashboardRouteRouteWithChildren
  '/mail': typeof mainMailRouteRoute
  '/unauthorized': typeof mainUnauthorizedRoute
  '/': typeof externalIndexRoute
  '/auth/forgot-password': typeof mainAuthForgotPasswordRouteRoute
  '/auth/login': typeof mainAuthLoginRouteRoute
  '/auth/register': typeof mainAuthRegisterRouteRoute
  '/auth/reset-password': typeof mainAuthResetPasswordRouteRoute
  '/auth/verify-email': typeof mainAuthVerifyEmailRouteRoute
  '/dashboard/adapters': typeof mainDashboardAdaptersRouteRoute
  '/dashboard/analytics': typeof mainDashboardAnalyticsRouteRoute
  '/dashboard/calendar': typeof mainDashboardCalendarRouteRoute
  '/dashboard/categories': typeof mainDashboardCategoriesRouteRoute
  '/dashboard/chat': typeof mainDashboardChatRouteRoute
  '/dashboard/coming-soon': typeof mainDashboardComingSoonRouteRoute
  '/dashboard/default': typeof mainDashboardDefaultRouteRoute
  '/dashboard/geo': typeof mainDashboardGeoRouteRoute
  '/dashboard/infrastructure': typeof mainDashboardInfrastructureRouteRoute
  '/dashboard/kanban': typeof mainDashboardKanbanRouteRoute
  '/dashboard/mail': typeof mainDashboardMailRouteRoute
  '/dashboard/media': typeof mainDashboardMediaRouteRoute
  '/dashboard/roles': typeof mainDashboardRolesRouteRoute
  '/dashboard/seo': typeof mainDashboardSeoRouteRoute
  '/dashboard/settings': typeof mainDashboardSettingsRouteRoute
  '/dashboard/social': typeof mainDashboardSocialRouteRoute
  '/dashboard/tasks': typeof mainDashboardTasksRouteRoute
  '/dashboard/users': typeof mainDashboardUsersRouteRoute
  '/dashboard/$': typeof mainDashboardSplatRoute
  '/dashboard/': typeof mainDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/chat': typeof mainChatRouteRoute
  '/mail': typeof mainMailRouteRoute
  '/unauthorized': typeof mainUnauthorizedRoute
  '/': typeof externalIndexRoute
  '/auth/forgot-password': typeof mainAuthForgotPasswordRouteRoute
  '/auth/login': typeof mainAuthLoginRouteRoute
  '/auth/register': typeof mainAuthRegisterRouteRoute
  '/auth/reset-password': typeof mainAuthResetPasswordRouteRoute
  '/auth/verify-email': typeof mainAuthVerifyEmailRouteRoute
  '/dashboard/adapters': typeof mainDashboardAdaptersRouteRoute
  '/dashboard/analytics': typeof mainDashboardAnalyticsRouteRoute
  '/dashboard/calendar': typeof mainDashboardCalendarRouteRoute
  '/dashboard/categories': typeof mainDashboardCategoriesRouteRoute
  '/dashboard/chat': typeof mainDashboardChatRouteRoute
  '/dashboard/coming-soon': typeof mainDashboardComingSoonRouteRoute
  '/dashboard/default': typeof mainDashboardDefaultRouteRoute
  '/dashboard/geo': typeof mainDashboardGeoRouteRoute
  '/dashboard/infrastructure': typeof mainDashboardInfrastructureRouteRoute
  '/dashboard/kanban': typeof mainDashboardKanbanRouteRoute
  '/dashboard/mail': typeof mainDashboardMailRouteRoute
  '/dashboard/media': typeof mainDashboardMediaRouteRoute
  '/dashboard/roles': typeof mainDashboardRolesRouteRoute
  '/dashboard/seo': typeof mainDashboardSeoRouteRoute
  '/dashboard/settings': typeof mainDashboardSettingsRouteRoute
  '/dashboard/social': typeof mainDashboardSocialRouteRoute
  '/dashboard/tasks': typeof mainDashboardTasksRouteRoute
  '/dashboard/users': typeof mainDashboardUsersRouteRoute
  '/dashboard/$': typeof mainDashboardSplatRoute
  '/dashboard': typeof mainDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(main)/chat': typeof mainChatRouteRoute
  '/(main)/dashboard': typeof mainDashboardRouteRouteWithChildren
  '/(main)/mail': typeof mainMailRouteRoute
  '/(main)/unauthorized': typeof mainUnauthorizedRoute
  '/(external)/': typeof externalIndexRoute
  '/(main)/auth/forgot-password': typeof mainAuthForgotPasswordRouteRoute
  '/(main)/auth/login': typeof mainAuthLoginRouteRoute
  '/(main)/auth/register': typeof mainAuthRegisterRouteRoute
  '/(main)/auth/reset-password': typeof mainAuthResetPasswordRouteRoute
  '/(main)/auth/verify-email': typeof mainAuthVerifyEmailRouteRoute
  '/(main)/dashboard/adapters': typeof mainDashboardAdaptersRouteRoute
  '/(main)/dashboard/analytics': typeof mainDashboardAnalyticsRouteRoute
  '/(main)/dashboard/calendar': typeof mainDashboardCalendarRouteRoute
  '/(main)/dashboard/categories': typeof mainDashboardCategoriesRouteRoute
  '/(main)/dashboard/chat': typeof mainDashboardChatRouteRoute
  '/(main)/dashboard/coming-soon': typeof mainDashboardComingSoonRouteRoute
  '/(main)/dashboard/default': typeof mainDashboardDefaultRouteRoute
  '/(main)/dashboard/geo': typeof mainDashboardGeoRouteRoute
  '/(main)/dashboard/infrastructure': typeof mainDashboardInfrastructureRouteRoute
  '/(main)/dashboard/kanban': typeof mainDashboardKanbanRouteRoute
  '/(main)/dashboard/mail': typeof mainDashboardMailRouteRoute
  '/(main)/dashboard/media': typeof mainDashboardMediaRouteRoute
  '/(main)/dashboard/roles': typeof mainDashboardRolesRouteRoute
  '/(main)/dashboard/seo': typeof mainDashboardSeoRouteRoute
  '/(main)/dashboard/settings': typeof mainDashboardSettingsRouteRoute
  '/(main)/dashboard/social': typeof mainDashboardSocialRouteRoute
  '/(main)/dashboard/tasks': typeof mainDashboardTasksRouteRoute
  '/(main)/dashboard/users': typeof mainDashboardUsersRouteRoute
  '/(main)/dashboard/$': typeof mainDashboardSplatRoute
  '/(main)/dashboard/': typeof mainDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/chat'
    | '/dashboard'
    | '/mail'
    | '/unauthorized'
    | '/'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/auth/verify-email'
    | '/dashboard/adapters'
    | '/dashboard/analytics'
    | '/dashboard/calendar'
    | '/dashboard/categories'
    | '/dashboard/chat'
    | '/dashboard/coming-soon'
    | '/dashboard/default'
    | '/dashboard/geo'
    | '/dashboard/infrastructure'
    | '/dashboard/kanban'
    | '/dashboard/mail'
    | '/dashboard/media'
    | '/dashboard/roles'
    | '/dashboard/seo'
    | '/dashboard/settings'
    | '/dashboard/social'
    | '/dashboard/tasks'
    | '/dashboard/users'
    | '/dashboard/$'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/chat'
    | '/mail'
    | '/unauthorized'
    | '/'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/auth/verify-email'
    | '/dashboard/adapters'
    | '/dashboard/analytics'
    | '/dashboard/calendar'
    | '/dashboard/categories'
    | '/dashboard/chat'
    | '/dashboard/coming-soon'
    | '/dashboard/default'
    | '/dashboard/geo'
    | '/dashboard/infrastructure'
    | '/dashboard/kanban'
    | '/dashboard/mail'
    | '/dashboard/media'
    | '/dashboard/roles'
    | '/dashboard/seo'
    | '/dashboard/settings'
    | '/dashboard/social'
    | '/dashboard/tasks'
    | '/dashboard/users'
    | '/dashboard/$'
    | '/dashboard'
  id:
    | '__root__'
    | '/(main)/chat'
    | '/(main)/dashboard'
    | '/(main)/mail'
    | '/(main)/unauthorized'
    | '/(external)/'
    | '/(main)/auth/forgot-password'
    | '/(main)/auth/login'
    | '/(main)/auth/register'
    | '/(main)/auth/reset-password'
    | '/(main)/auth/verify-email'
    | '/(main)/dashboard/adapters'
    | '/(main)/dashboard/analytics'
    | '/(main)/dashboard/calendar'
    | '/(main)/dashboard/categories'
    | '/(main)/dashboard/chat'
    | '/(main)/dashboard/coming-soon'
    | '/(main)/dashboard/default'
    | '/(main)/dashboard/geo'
    | '/(main)/dashboard/infrastructure'
    | '/(main)/dashboard/kanban'
    | '/(main)/dashboard/mail'
    | '/(main)/dashboard/media'
    | '/(main)/dashboard/roles'
    | '/(main)/dashboard/seo'
    | '/(main)/dashboard/settings'
    | '/(main)/dashboard/social'
    | '/(main)/dashboard/tasks'
    | '/(main)/dashboard/users'
    | '/(main)/dashboard/$'
    | '/(main)/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  mainChatRouteRoute: typeof mainChatRouteRoute
  mainDashboardRouteRoute: typeof mainDashboardRouteRouteWithChildren
  mainMailRouteRoute: typeof mainMailRouteRoute
  mainUnauthorizedRoute: typeof mainUnauthorizedRoute
  externalIndexRoute: typeof externalIndexRoute
  mainAuthForgotPasswordRouteRoute: typeof mainAuthForgotPasswordRouteRoute
  mainAuthLoginRouteRoute: typeof mainAuthLoginRouteRoute
  mainAuthRegisterRouteRoute: typeof mainAuthRegisterRouteRoute
  mainAuthResetPasswordRouteRoute: typeof mainAuthResetPasswordRouteRoute
  mainAuthVerifyEmailRouteRoute: typeof mainAuthVerifyEmailRouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(external)/': {
      id: '/(external)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof externalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)/chat': {
      id: '/(main)/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof mainChatRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)/dashboard': {
      id: '/(main)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof mainDashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)/mail': {
      id: '/(main)/mail'
      path: '/mail'
      fullPath: '/mail'
      preLoaderRoute: typeof mainMailRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)/unauthorized': {
      id: '/(main)/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof mainUnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)/auth/forgot-password': {
      id: '/(main)/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof mainAuthForgotPasswordRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)/auth/login': {
      id: '/(main)/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof mainAuthLoginRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)/auth/register': {
      id: '/(main)/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof mainAuthRegisterRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)/auth/reset-password': {
      id: '/(main)/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof mainAuthResetPasswordRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)/auth/verify-email': {
      id: '/(main)/auth/verify-email'
      path: '/auth/verify-email'
      fullPath: '/auth/verify-email'
      preLoaderRoute: typeof mainAuthVerifyEmailRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)/dashboard/': {
      id: '/(main)/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof mainDashboardIndexRouteImport
      parentRoute: typeof mainDashboardRouteRoute
    }
    '/(main)/dashboard/$': {
      id: '/(main)/dashboard/$'
      path: '/$'
      fullPath: '/dashboard/$'
      preLoaderRoute: typeof mainDashboardSplatRouteImport
      parentRoute: typeof mainDashboardRouteRoute
    }
    '/(main)/dashboard/adapters': {
      id: '/(main)/dashboard/adapters'
      path: '/adapters'
      fullPath: '/dashboard/adapters'
      preLoaderRoute: typeof mainDashboardAdaptersRouteRouteImport
      parentRoute: typeof mainDashboardRouteRoute
    }
    '/(main)/dashboard/analytics': {
      id: '/(main)/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof mainDashboardAnalyticsRouteRouteImport
      parentRoute: typeof mainDashboardRouteRoute
    }
    '/(main)/dashboard/calendar': {
      id: '/(main)/dashboard/calendar'
      path: '/calendar'
      fullPath: '/dashboard/calendar'
      preLoaderRoute: typeof mainDashboardCalendarRouteRouteImport
      parentRoute: typeof mainDashboardRouteRoute
    }
    '/(main)/dashboard/categories': {
      id: '/(main)/dashboard/categories'
      path: '/categories'
      fullPath: '/dashboard/categories'
      preLoaderRoute: typeof mainDashboardCategoriesRouteRouteImport
      parentRoute: typeof mainDashboardRouteRoute
    }
    '/(main)/dashboard/chat': {
      id: '/(main)/dashboard/chat'
      path: '/chat'
      fullPath: '/dashboard/chat'
      preLoaderRoute: typeof mainDashboardChatRouteRouteImport
      parentRoute: typeof mainDashboardRouteRoute
    }
    '/(main)/dashboard/coming-soon': {
      id: '/(main)/dashboard/coming-soon'
      path: '/coming-soon'
      fullPath: '/dashboard/coming-soon'
      preLoaderRoute: typeof mainDashboardComingSoonRouteRouteImport
      parentRoute: typeof mainDashboardRouteRoute
    }
    '/(main)/dashboard/default': {
      id: '/(main)/dashboard/default'
      path: '/default'
      fullPath: '/dashboard/default'
      preLoaderRoute: typeof mainDashboardDefaultRouteRouteImport
      parentRoute: typeof mainDashboardRouteRoute
    }
    '/(main)/dashboard/geo': {
      id: '/(main)/dashboard/geo'
      path: '/geo'
      fullPath: '/dashboard/geo'
      preLoaderRoute: typeof mainDashboardGeoRouteRouteImport
      parentRoute: typeof mainDashboardRouteRoute
    }
    '/(main)/dashboard/infrastructure': {
      id: '/(main)/dashboard/infrastructure'
      path: '/infrastructure'
      fullPath: '/dashboard/infrastructure'
      preLoaderRoute: typeof mainDashboardInfrastructureRouteRouteImport
      parentRoute: typeof mainDashboardRouteRoute
    }
    '/(main)/dashboard/kanban': {
      id: '/(main)/dashboard/kanban'
      path: '/kanban'
      fullPath: '/dashboard/kanban'
      preLoaderRoute: typeof mainDashboardKanbanRouteRouteImport
      parentRoute: typeof mainDashboardRouteRoute
    }
    '/(main)/dashboard/mail': {
      id: '/(main)/dashboard/mail'
      path: '/mail'
      fullPath: '/dashboard/mail'
      preLoaderRoute: typeof mainDashboardMailRouteRouteImport
      parentRoute: typeof mainDashboardRouteRoute
    }
    '/(main)/dashboard/media': {
      id: '/(main)/dashboard/media'
      path: '/media'
      fullPath: '/dashboard/media'
      preLoaderRoute: typeof mainDashboardMediaRouteRouteImport
      parentRoute: typeof mainDashboardRouteRoute
    }
    '/(main)/dashboard/roles': {
      id: '/(main)/dashboard/roles'
      path: '/roles'
      fullPath: '/dashboard/roles'
      preLoaderRoute: typeof mainDashboardRolesRouteRouteImport
      parentRoute: typeof mainDashboardRouteRoute
    }
    '/(main)/dashboard/seo': {
      id: '/(main)/dashboard/seo'
      path: '/seo'
      fullPath: '/dashboard/seo'
      preLoaderRoute: typeof mainDashboardSeoRouteRouteImport
      parentRoute: typeof mainDashboardRouteRoute
    }
    '/(main)/dashboard/settings': {
      id: '/(main)/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof mainDashboardSettingsRouteRouteImport
      parentRoute: typeof mainDashboardRouteRoute
    }
    '/(main)/dashboard/social': {
      id: '/(main)/dashboard/social'
      path: '/social'
      fullPath: '/dashboard/social'
      preLoaderRoute: typeof mainDashboardSocialRouteRouteImport
      parentRoute: typeof mainDashboardRouteRoute
    }
    '/(main)/dashboard/tasks': {
      id: '/(main)/dashboard/tasks'
      path: '/tasks'
      fullPath: '/dashboard/tasks'
      preLoaderRoute: typeof mainDashboardTasksRouteRouteImport
      parentRoute: typeof mainDashboardRouteRoute
    }
    '/(main)/dashboard/users': {
      id: '/(main)/dashboard/users'
      path: '/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof mainDashboardUsersRouteRouteImport
      parentRoute: typeof mainDashboardRouteRoute
    }
  }
}

interface mainDashboardRouteRouteChildren {
  mainDashboardAdaptersRouteRoute: typeof mainDashboardAdaptersRouteRoute
  mainDashboardAnalyticsRouteRoute: typeof mainDashboardAnalyticsRouteRoute
  mainDashboardCalendarRouteRoute: typeof mainDashboardCalendarRouteRoute
  mainDashboardCategoriesRouteRoute: typeof mainDashboardCategoriesRouteRoute
  mainDashboardChatRouteRoute: typeof mainDashboardChatRouteRoute
  mainDashboardComingSoonRouteRoute: typeof mainDashboardComingSoonRouteRoute
  mainDashboardDefaultRouteRoute: typeof mainDashboardDefaultRouteRoute
  mainDashboardGeoRouteRoute: typeof mainDashboardGeoRouteRoute
  mainDashboardInfrastructureRouteRoute: typeof mainDashboardInfrastructureRouteRoute
  mainDashboardKanbanRouteRoute: typeof mainDashboardKanbanRouteRoute
  mainDashboardMailRouteRoute: typeof mainDashboardMailRouteRoute
  mainDashboardMediaRouteRoute: typeof mainDashboardMediaRouteRoute
  mainDashboardRolesRouteRoute: typeof mainDashboardRolesRouteRoute
  mainDashboardSeoRouteRoute: typeof mainDashboardSeoRouteRoute
  mainDashboardSettingsRouteRoute: typeof mainDashboardSettingsRouteRoute
  mainDashboardSocialRouteRoute: typeof mainDashboardSocialRouteRoute
  mainDashboardTasksRouteRoute: typeof mainDashboardTasksRouteRoute
  mainDashboardUsersRouteRoute: typeof mainDashboardUsersRouteRoute
  mainDashboardSplatRoute: typeof mainDashboardSplatRoute
  mainDashboardIndexRoute: typeof mainDashboardIndexRoute
}

const mainDashboardRouteRouteChildren: mainDashboardRouteRouteChildren = {
  mainDashboardAdaptersRouteRoute: mainDashboardAdaptersRouteRoute,
  mainDashboardAnalyticsRouteRoute: mainDashboardAnalyticsRouteRoute,
  mainDashboardCalendarRouteRoute: mainDashboardCalendarRouteRoute,
  mainDashboardCategoriesRouteRoute: mainDashboardCategoriesRouteRoute,
  mainDashboardChatRouteRoute: mainDashboardChatRouteRoute,
  mainDashboardComingSoonRouteRoute: mainDashboardComingSoonRouteRoute,
  mainDashboardDefaultRouteRoute: mainDashboardDefaultRouteRoute,
  mainDashboardGeoRouteRoute: mainDashboardGeoRouteRoute,
  mainDashboardInfrastructureRouteRoute: mainDashboardInfrastructureRouteRoute,
  mainDashboardKanbanRouteRoute: mainDashboardKanbanRouteRoute,
  mainDashboardMailRouteRoute: mainDashboardMailRouteRoute,
  mainDashboardMediaRouteRoute: mainDashboardMediaRouteRoute,
  mainDashboardRolesRouteRoute: mainDashboardRolesRouteRoute,
  mainDashboardSeoRouteRoute: mainDashboardSeoRouteRoute,
  mainDashboardSettingsRouteRoute: mainDashboardSettingsRouteRoute,
  mainDashboardSocialRouteRoute: mainDashboardSocialRouteRoute,
  mainDashboardTasksRouteRoute: mainDashboardTasksRouteRoute,
  mainDashboardUsersRouteRoute: mainDashboardUsersRouteRoute,
  mainDashboardSplatRoute: mainDashboardSplatRoute,
  mainDashboardIndexRoute: mainDashboardIndexRoute,
}

const mainDashboardRouteRouteWithChildren =
  mainDashboardRouteRoute._addFileChildren(mainDashboardRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  mainChatRouteRoute: mainChatRouteRoute,
  mainDashboardRouteRoute: mainDashboardRouteRouteWithChildren,
  mainMailRouteRoute: mainMailRouteRoute,
  mainUnauthorizedRoute: mainUnauthorizedRoute,
  externalIndexRoute: externalIndexRoute,
  mainAuthForgotPasswordRouteRoute: mainAuthForgotPasswordRouteRoute,
  mainAuthLoginRouteRoute: mainAuthLoginRouteRoute,
  mainAuthRegisterRouteRoute: mainAuthRegisterRouteRoute,
  mainAuthResetPasswordRouteRoute: mainAuthResetPasswordRouteRoute,
  mainAuthVerifyEmailRouteRoute: mainAuthVerifyEmailRouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
